version: "3.4"

services:
  frontend:
    container_name: finnet-frontend
    image: finnet-frontend
    build:
      context: .
      target: production
    volumes:
      - .:/app/
    ports:
      - 80:80