version: "3.5"

services:
  frontend:
    container_name: finnet-frontend
    image: ${DOCKER_HUB_REPO}/finnet-frontend
    networks:
      - finnet
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    ports:
      - 80:80
      - 443:443

    
networks:
  finnet:
    external: true
    name: finnet