version: "3.3"

services:
  frontend:
    container_name: finnet-frontend
    image: finnet-frontend
    build:
      context: .
      target: production
    volumes:
      - ./src:/app/src
    ports:
      - 80:80