name: Deploy to VPS

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and Push All Images
        run: |
          echo "Build Version: $GITHUB_RUN_NUMBER" > ./public/version.txt
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: srv19.mikr.us
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 10152
          script: |
            cd Finnet---Frontend
            bash deploy/deploy.sh