name: Deploy to VPS

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: srv19.mikr.us
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 10152
          script: |
            cd Finnet---Frontend
            bash deploy/deploy.sh